config/routes.rb
Rails.application.routes.draw do
  # static pages
  root 'statics#index'

  # users
  devise_for :users, path: 'accounts', controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks',
    sessions: 'users/sessions'
  }

  # customize user routes for matching codepen
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
  end

  # products
  get '/accounts/pro', to: 'products#index', as: 'products'
  get '/accounts/pro/billing/:plan/:period', to: 'products#show', as: 'product'

  # pens
  get '/your-work', to: 'pens#index', as: 'pens'
  get 'follow', to: 'pens#follow', as: 'follow'
  get 'trending', to: 'pens#trending', as: 'trending'
  get '/pen', to: 'pens#new', as: 'new_pen'
  get '/:username/details/:random_url', to: 'pens#show', as: 'pen'
  get '/:username/pen/:random_url', to: 'pens#edit', as: 'edit_pen'
  get '/search/pens',  to: 'pens#search_all_users', as: 'search_all_users_pens'
  delete '/:username/pen/:random_url', to: 'pens#destroy', as: 'destroy_pen'

  # comments
  post '/:username/details/:random_url', to: 'comments#create', as: 'create_comment'
  resources :comments, only: [:destroy]

  # orders
  resources :orders, only: [:new]

  # api
  namespace :api, default: { format: :json } do
    namespace :v1 do
      resources :pens, only: [:create, :edit, :update], param: :random_url do
        member do
          get :love, action: 'love_pen'
          post :love, action: 'love_list'
          post :pin, action: 'pin_create'
          post :private, action: 'private_toggle'
          # resources :pins, only: [:index, :create]
        end

        collection do
          get 'grid/:page', action: 'grid'
          get 'search/grid/:page', action: 'grid_search'
          get :pins, action: 'pin_list'
        end
      end
      resources :deleted_pens, only: [:update, :destroy], param: :random_url

      # users
      resource :user, only: [] do
        collection do
          get 'follow', to: 'follows#list'
          post 'follow', to: 'follows#follow'
          post 'unfollow', to: 'follows#unfollow'
          get 'membership', to: 'users#membership'
          get 'check_user', to: 'users#check_user'
        end
      end

      # orders
      resources :orders, only: [:create] do
        collection do
          post :result
          get :client
        end
      end
      # comments
      resources :comments, only: [:index, :create, :update, :destroy]
      # cdn_resources
      resources :resources, only: [:create, :destroy]
    end
  end
end

app/views/shared/_edit_footer.html.erb
<footer class="edit-footer">
</footer>

app/views/shared/_edit_header.html.erb
<header class="edit-header">
  <div class="edit-title-header">
    <%= link_to pens_path do %>
      <%= image_tag "/images/logo-s.svg", alt: "CodePain" %>
    <% end %>

    <div class="edit-title-area">
      <div class="edit-title-wrap">
        <h1 id='edit-title'><%= 'Untitled' if action_name == 'new' %></h1>
        <span id='btn-edit-title'><i class="fas fa-pencil-alt"></i></span>
        <input type="text" id="input-title" value="" style='display: none;'>
      </div>
      <div class="edit-username">
        <div class="edit-author" id="username"><%= show_username %></div>
        <span class="logo-pro edit-pro-icon">pro</span>
      </div>
    </div>
  </div>
  <div class="edit-btn-header">
    <div class="burger-btn">
      <button>
        <span></span>
        <div class="fas fa-chevron-down"></div>
      </button>
    </div>
    <div class="edit-btn-wrap">
      <%= private_switch %>
      <% if user_signed_in? && action_name == 'edit' %>
        <button class="btn-Love" data-controller="stats"
                                data-stats-target="editor"
                                data-action="click->stats#toggleEditorHeart"
                                data-stats-loved-class="love-active">
          <span><i class="fas fa-heart stroke-current"
                  data-stats-target="heart"></i>
          </span>
        </button>
      <% end %>
      <%= save_button %>
      <%= save_as_private_button %>
      <button class="btn-settings" id="btn-settings"><span><i  class="fas fa-cog"></i></span>Settings</button>
    </div>
  </div>
  <%= user_menu_button %>
</header>

app/views/shared/_footer.html.erb
<footer class="footer-container">
  <div class="footer-items-wrap">
    <div class="footer-item">
      <h2 class="footer-item-title">Team</h2>
      <div class="footer-item-team-wrap">
        <ul class="footer-item-team">
          <li class="github-icon"><i class="fab fa-github"></i></li>
          <li>
            <a href="https://github.com/VincentYuuu" class="teams-mem-link" target="_blank" rel="noreferrer noopener" title="游維鴻 GitHub">VincentYuuu</a>
          </li>
          <li>
            <a href="https://github.com/senri8468" class="teams-mem-link" target="_blank" rel="noreferrer noopener" title="黃宇鈞 GitHub">senri8468</a>
          </li>
          <li>
            <a href="https://github.com/Mandy0315" class="teams-mem-link" target="_blank" rel="noreferrer noopener" title="蔡敏佳 GitHub">Mandy0315</a>
          </li>
        </ul>
        <ul class="footer-item-team">
          <li>
            <a href="https://github.com/p4952015" class="teams-mem-link" target="_blank" rel="noreferrer noopener" title="劉盈希 GitHub">p4952015</a>
          </li>
          <li>
            <a href="https://github.com/cyhsujohn" class="teams-mem-link" target="_blank" rel="noreferrer noopener" title="許朝詠 GitHub">cyhsujohn</a>
          </li>
          <li>
            <a href="https://github.com/yentingli" class="teams-mem-link" target="_blank" rel="noreferrer noopener" title="李彥廷 GitHub">yentingli</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="footer-dev">
      <h2 class="footer-item-title">Frontend</h2>
      <ul class="footer-item-dev">
        <li>TailwindCSS</li>
        <li>JavaScript</li>
        <li>React</li>
        <li>Stimulus</li>
        <li>Ace</li>
      </ul>
    </div>
    <div class="footer-dev">
      <h2 class="footer-item-title">Backend</h2>
      <ul class="footer-item-dev">
        <li>Ruby on Rails</li>
      </ul>
    </div>
    <div class="footer-dev">
      <h2 class="footer-item-title">API</h2>
      <ul class="footer-item-dev">
        <li>Blueprinter</li>
        <li>jBuilder</li>
        <li>Social login</li>
        <li>ECPay</li>
      </ul>
    </div>
    <div class="footer-dev">
      <h2 class="footer-item-title">Others</h2>
      <ul class="footer-item-dev">
        <li>GitHub</li>
        <li>PostgreSQL</li>
        <li>Heroku</li>
        <li>cdnjs</li>
      </ul>
    </div>



  </div>

  <div class="footer-logo-wrap">
    <a class="footer-logo" href="/">
      <img src="/images/logo-white.svg" alt="codePain-logo">
    </a>
    <a class="footer-logo-s" href="/">
      <%= image_tag "/images/logo-s.svg", alt: "CodePain" %>
    </a>
    <p class="footer-logo-copy">&copy;2021 CodePain.</p>
    <p class="footer-logo-text">
      A serious CodePen clone project.<br>
    </p>
    <a href="https://github.com/6yCRYSTAL/codepain"
       class="teams-mem-link"
       target="_blank"
       rel="noreferrer noopener"
       title="codepain-repo">
        <i class="github-icon fab fa-github"></i>
        CodePain by 6yCRYSTAL
    </a>
  </div>
</footer>

app/views/shared/_logged_in.html.erb
<div class="container" data-sidebar-open="true">
  <%= render 'shared/sidebar' %>
  <%= render 'shared/usermenu_signout' %>
</div>

app/views/shared/_not_logged_in.html.erb
<div class="container" data-sidebar-open="true">
  <%= render 'shared/sidebar' %>
  <%= render 'shared/usermenu_signin' %>
  <main>
    <%= link_to '這是暫時按鈕可以連到Your-work頁面', pens_path %>
  </main>
  <%= render 'shared/footer' %>
</div>

app/views/shared/_pin.html.erb
<div class="-btpinnedn">
  <button class="btn-pinned">
    <span><i  class="fas fa-thumbtack"></i></span>
    <svg class="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24"></svg>
  </button>
  <button class="btn-pin-arrow">
    <span class="fas fa-chevron-down"></span>
  </button>
</div>
<div class="extend">
  <div class="Pinned-Items">
    Pinned Items
  </div>
  <div class="list">
    <ul>
      <li>
        <i class="fas fa-window-maximize icon-a"></i>
        <button class="item"><i class="delete fas fa-times"></i></button>
      </li>
      <li class="my-pin">
        <i class="fas fa-window-maximize icon-a"></i>
        <button class="item"><i class="delete fas fa-times"></i></button>
      </li>
      <li class="my-pin">
        <i class="fas fa-window-maximize icon-a"></i>
        <button class="item"><i class="delete fas fa-times"></i></button>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_private_switch.html.erb
<div class="private-switch-wrap" data-controller="private" data-private-random-value="<%= @pen.random_url %>">
  <div class="private-lock hidden" id="private-lock" data-private-target="privateIcons"><i class="fas fa-lock"></i></div>
  <div class="private-switch" id="private-switch">
    Private
    <label for="btn-private-switch" class="private-switch-label" data-action="click->private#togglePrivate">
      <div>
        <input type="checkbox"
               id="btn-private-switch"
               class="sr-only"
               data-private-target="privateChecks"
               data-action="click->private#stopPropagation">
        <div class="block"></div>
        <div class="dot"></div>
      </div>
    </label>
    Public
  </div>
</div>

app/views/shared/_show_header.html.erb
<header class="edit-header">
  <div class="edit-title-header">
    <%= link_to pens_path do %>
      <%= image_tag "/images/logo-s.svg", alt: "CodePain" %>
    <% end %>

    <div class="edit-title-area">
      <h1 id='edit-title'>Untitled</h1>
      <span id='btn-edit'><i class="fas fa-pencil-alt"></i></span>
      <input type="text" id="inputTitle" value='Untitled' style='display: none;'>
      <div class="edit-author" id="username"><%= @pen.user.username %></div>
    </div>
  </div>
  <div class="edit-btn-header">
    <button class="btn-Love"><span><i class="fas fa-heart"></i></span></button>
    <%# <button class="btn-save" id="btn-save"><span><i class="fas fa-cloud"></i></span>Save</button> %>
    <%# <div id="btn-update" style="color: white; cursor: pointer;">update</div> %>
    <button class="btn-settings"><span><i  class="fas fa-cog"></i></span>Settings</button>
    <button class="btn-changeView">
      <span>
        <svg viewBox="-703.9 491.1 31.7 25.3">
          <path
            d="M-688.1 499.6c-4.3 0-8.1 2.2-10.4 5.6 2.2 3.4 6 5.6 10.4 5.6 4.3 0 8.1-2.2 10.4-5.6-2.2-3.3-6-5.6-10.4-5.6zm0 9.9c-2.3 0-4.2-1.9-4.2-4.2-.1-2.4 1.8-4.3 4.2-4.3 2.3 0 4.2 1.9 4.2 4.2 0 2.4-1.9 4.3-4.2 4.3z">
          </path>
          <path
            d="M-673.4 491.1h-29.3c-.7 0-1.2.5-1.2 1.2v22.9c0 .7.5 1.2 1.2 1.2h29.3c.7 0 1.2-.5 1.2-1.2v-22.9c0-.6-.6-1.2-1.2-1.2zm-28.1 22.9v-17.1h26.8V514h-26.8z">
          </path>
        </svg>
      </span>
      Change View</button>
      <div class="pinned-btn">
        <button class="btn-pinned">
          <span><i  class="fas fa-thumbtack"></i></span>
          <svg class="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24"></svg>
        </button>
        <button class="btn-pin-arrow">
          <span class="fas fa-chevron-down"></span>
        </button>
        </div>
        <div class="extend">
        <div class="Pinned-Items">
        Pinned Items
        </div>
        <div class="list">
        <ul>
          <li>
            <i class="fas fa-window-maximize icon-a"></i>
            <button class="item"><i class="delete fas fa-times"></i></button>
          </li>
          <li class="my-pin">
            <i class="fas fa-window-maximize icon-a"></i>
            <button class="item"><i class="delete fas fa-times"></i></button>
          </li>
          <li class="my-pin">
            <i class="fas fa-window-maximize icon-a"></i>
            <button class="item"><i class="delete fas fa-times"></i></button>
          </li>
      </div>
    </div>
  </div>
  <%= render 'shared/user_menu_box' %>
</header>

app/views/shared/_sidebar.html.erb
<header class="main-sidebar" data-burger-target="sidebar">
  <div class="sidebar-logo">
    <a href="/">
      <img src="/images/logo-white.svg" alt="codepain-logo">
    </a>
  </div>
  <div class="sidebar-toggle-btn">
    <button>
      <span></span>
      <div class="fas fa-chevron-left"></div>
    </button>
    <div class="sidebar-line"></div>
  </div>
  <% if current_user %>
    <div class="sidebar-content">
      <div class="sidebar-item">
        <p class="sidebar-title">CREATE</p>
        <div class="sidebar-item-line"></div>
        <%= link_to new_pen_path,class: 'create-link' do %>
          <svg viewBox="0 0 20 20" width="20" height="20">
          <path
          d="M0 9.002C0 8.45.455 8 .992 8h18.016c.548 0 .992.456.992 1.002v9.996c0 .553-.455 1.002-.992 1.002H.992C.444 20 0 19.544 0 18.998V9.002zm0-8C0 .45.451 0 .99 0h4.02A.99.99 0 016 1.003v4.994C6 6.551 5.549 7 5.01 7H.99A.99.99 0 010 5.997V1.003zm7 0C7 .45 7.451 0 7.99 0h4.02A.99.99 0 0113 1.003v4.994C13 6.551 12.549 7 12.01 7H7.99A.99.99 0 017 5.997V1.003zm7 0C14 .45 14.451 0 14.99 0h4.02A.99.99 0 0120 1.003v4.994C20 6.551 19.549 7 19.01 7h-4.02A.99.99 0 0114 5.997V1.003z">
          </path>
          </svg>
          <span>Pen</span>
        <% end %>
      </div>
      <div class="sidebar-item sidebar-item-line">
        <%= link_to 'Your work' , pens_path %>
        <%= link_to 'Following' , follow_path %>
        <%= link_to 'Trending' , trending_path %>
      </div>
      <div class="sidebar-item sidebar-item-line">
        <%= link_to products_path,class:'codepain-link' do%>
          <p>CodePain</p>
          <span class="logo-pro">pro</span>
          <% end %>
      </div>
      <figure class="sidebar-advertise">
        <div class="advertise-img">
          <a href="https://astro.5xruby.tw/" rel="noreferrer noopener nofollow" target="_blank">
            <img src="/images/banner-5x.jpg" title="5X宣傳廣告">
          </a>
        </div>
        <figcaption>5X宣傳廣告</figcaption>
      </figure>
    </div>
  <% else %>
    <div class="sidebar-content-logout">
      <div class="sidebar-item">
        <p class="sidebar-title">Try Our Online Editor</p>
        <%= link_to new_pen_path,class: 'start-code' do %>
          <span>Start Coding</span>
        <% end %>
      </div>
      <div class="sidebar-item sidebar-item-line2">
        <%= link_to products_path, class:'codepain-link' do%>
          <p>CodePain</p>
          <span class="logo-pro">pro</span>
        <% end %>
      </div>
      <figure class="sidebar-advertise">
        <div class="advertise-img">
          <a href="https://astro.5xruby.tw/" rel="noreferrer noopener nofollow" target="_blank">
            <img src="/images/banner-5x.jpg" title="5X宣傳廣告">
          </a>
        </div>
        <figcaption>5X宣傳廣告</figcaption>
      </figure>
    </div>
  <% end %>
</header>

app/views/shared/_user_menu_box.html.erb
<div class="userMenu-box">
  <button class="userMenu-img" id="userMenu-btn">
    <img
      src="/images/user-img.jpg"
      alt="使用者圖像" />
  </button>
  <div class="userMenu-topnav-wrap">
    <ul class="userMenu-topnav">
      <li><%= link_to  "Your Work", pens_path %></li>
      <li><%= link_to  "New Pen", new_pen_path %></li>
      <li><%= link_to products_path do %>
            <span>Upgrade to</span>
            <span class="logo-pro">pro</span>
          <% end %>
      </li>
      <li>
        <%= link_to logout_path, method: :delete, class: 'userMenu-icon' do %>
          <svg viewBox="0 0 98.28 68.04" width="20px" height="20px">
            <path fill="none" d="M82.78 0h15.5v68.04h-15.5z"></path>
            <path d="M0 0h.51v68.04H0zM56 47.11V60.1H8.39V7.94H56v12.99h7.88V0H.51v68.04h63.37V47.11H56z"></path>
            <path fill="none" d="M0 0h22.97v68.04H0z"></path>
            <path d="M41.87 38.04h40.85l-9.93 9.9 5.63 5.67 19.35-19.49-19.35-19.48-5.63 5.57L82.51 30H41.87v8.04z"></path>
          </svg>
          <span>Log Out</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_usermenu_signin.html.erb
<!-- 登入 -->
<section class="search-userMenu-container">
  <div class="search-userMenu">
    <%= link_to root_path, class: 'burger-logo' do%>
      <img src="/images/logo-crystal-white.svg" alt="logo" />
    <% end %>
    <div class="burger-menu"
         data-burger-target="burger">
      <button>
        <span></span>
        <div class="fas fa-chevron-down"></div>
      </button>
    </div>
    <%= form_tag search_all_users_pens_path, method: 'get', class: 'search-box' do %>
      <label>
        <div class="fas fa-search"></div>
        <%= text_field_tag :q, params[:q],
                               placeholder: 'Search CodePain...',
                               class: 'search-text' %>
      </label>
    <% end %>

    <%= render 'shared/user_menu_box' %>
  </div>
</section>

app/views/shared/_usermenu_signout.html.erb
<!-- 登出 -->
<section class="search-userMenu-container">
  <div class="search-userMenu">
    <%= link_to root_path, class: 'burger-logo' do%>
      <img src="/images/logo-crystal-white.svg" alt="logo" />
    <% end %>
    <div class="burger-menu"
         data-burger-target="burger">
      <button>
        <span></span>
        <div class="fas fa-chevron-down"></div>
      </button>
    </div>
    <%# search all users' pens bar %>
    <%= form_tag search_all_users_pens_path, method: 'get', class: 'search-box' do %>
      <label>
        <div class="fas fa-search"></div>
        <%= text_field_tag :q, params[:q],
                               placeholder: 'Search CodePain...',
                               class: 'search-text' %>
      </label>
    <% end %>

    <%= signup_button %>
    <%= login_button %>

  </div>
</section>